**Name**: Kamran Khan

**Batch**: B1

**Class**: TY - CSE AIML

**Roll No**: 11

<h1 align="center">Computing Lab - II | Experiment No - 3</h1>

**Aim**: Dataset handling using python

**objective**: The objective of this experiment is to familiarize ourselves with the process of handling datasets using the Pandas library in Python. This involves loading datasets, exploring their structure, and performing basic data manipulation and analysis.

**Theory**:

**Pandas**: Pandas is an open-source library that provides high-level data structures and functions designed to make data analysis fast and easy in Python. Its main data structures are the Series and the DataFrame.
           
- **Series**: A one-dimensional labeled array that can hold data of any type. It's similar to a column in a spreadsheet or a single column of a database table.

- **DataFrame**: A two-dimensional labeled data structure with columns that can be of different types. It's like a spreadsheet or a SQL table, where each column can be thought of as a Series.
        
Pandas offers a wide range of functions for data manipulation, cleaning, merging, grouping, and more. It's commonly used for data preprocessing and exploration in data science and analysis tasks.

**NumPy**: NumPy, short for "Numerical Python," is a fundamental Python library that provides support for multi-dimensional arrays and matrices, along with a wide range of mathematical functions to efficiently perform numerical computations. It's a cornerstone library for scientific computing and data analysis, offering high-performance operations on arrays and facilitating tasks like linear algebra, statistical calculations, and more.

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('IMDb_top_1000.csv')
pd.read_csv('IMDb_top_1000.csv')

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

1. **head()**: The head() function is used to retrieve the first few rows of a DataFrame. By default, it returns the first 5 rows of the DataFrame, but you can specify the number of rows you want to see by passing an argument to the function.

In [4]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

2. **tail()**: The tail() function is used to retrieve the last few rows of a DataFrame. Just like head(), it helps you quickly inspect the structure and content of the DataFrame, but from the end of the dataset. By default, tail() returns the last 5 rows, but you can specify the number of rows you want to see by passing an argument to the function.

In [5]:
df.tail()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

3. **loc[]**: The loc[] indexer is used to access a group of rows and columns by label(s) or a boolean array. It allows you to select data based on the labels of rows and columns in a DataFrame. The loc[] indexer is particularly useful when you want to retrieve specific rows and columns using their row and column labels.

In [6]:
df.loc[10 : 20]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
10,https://m.media-amazon.com/images/M/MV5BN2EyZj...,The Lord of the Rings: The Fellowship of the Ring,2001,U,178 min,"Action, Adventure, Drama",8.8,A meek Hobbit from the Shire and eight compani...,92.0,Peter Jackson,Elijah Wood,Ian McKellen,Orlando Bloom,Sean Bean,1661481,"315,544,750"
11,https://m.media-amazon.com/images/M/MV5BNWIwOD...,Forrest Gump,1994,UA,142 min,"Drama, Romance",8.8,"The presidencies of Kennedy and Johnson, the e...",82.0,Robert Zemeckis,Tom Hanks,Robin Wright,Gary Sinise,Sally Field,1809221,"330,252,182"
12,https://m.media-amazon.com/images/M/MV5BOTQ5ND...,"Il buono, il brutto, il cattivo",1966,A,161 min,Western,8.8,A bounty hunting scam joins two men in an unea...,90.0,Sergio Leone,Clint Eastwood,Eli Wallach,Lee Van Cleef,Aldo Giuffrè,688390,"6,100,000"
13,https://m.media-amazon.com/images/M/MV5BZGMxZT...,The Lord of the Rings: The Two Towers,2002,UA,179 min,"Action, Adventure, Drama",8.7,While Frodo and Sam edge closer to Mordor with...,87.0,Peter Jackson,Elijah Wood,Ian McKellen,Viggo Mortensen,Orlando Bloom,1485555,"342,551,365"
14,https://m.media-amazon.com/images/M/MV5BNzQzOT...,The Matrix,1999,A,136 min,"Action, Sci-Fi",8.7,When a beautiful stranger leads computer hacke...,73.0,Lana Wachowski,Lilly Wachowski,Keanu Reeves,Laurence Fishburne,Carrie-Anne Moss,1676426,"171,479,930"
15,https://m.media-amazon.com/images/M/MV5BY2NkZj...,Goodfellas,1990,A,146 min,"Biography, Crime, Drama",8.7,The story of Henry Hill and his life in the mo...,90.0,Martin Scorsese,Robert De Niro,Ray Liotta,Joe Pesci,Lorraine Bracco,1020727,"46,836,394"
16,https://m.media-amazon.com/images/M/MV5BYmU1ND...,Star Wars: Episode V - The Empire Strikes Back,1980,UA,124 min,"Action, Adventure, Fantasy",8.7,After the Rebels are brutally overpowered by t...,82.0,Irvin Kershner,Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,1159315,"290,475,067"
17,https://m.media-amazon.com/images/M/MV5BZjA0OW...,One Flew Over the Cuckoo's Nest,1975,A,133 min,Drama,8.7,A criminal pleads insanity and is admitted to ...,83.0,Milos Forman,Jack Nicholson,Louise Fletcher,Michael Berryman,Peter Brocco,918088,"112,000,000"
18,https://m.media-amazon.com/images/M/MV5BNjViNW...,Hamilton,2020,PG-13,160 min,"Biography, Drama, History",8.6,The real life of one of America's foremost fou...,90.0,Thomas Kail,Lin-Manuel Miranda,Phillipa Soo,Leslie Odom Jr.,Renée Elise Goldsberry,55291,NaN
19,https://m.media-amazon.com/images/M/MV5BYWZjMj...,Gisaengchung,2019,A,132 min,"Comedy, Drama, Thriller",8.6,Greed and class discrimination threaten the ne...,96.0,Bong Joon Ho,Kang-ho Song,Lee Sun-kyun,Cho Yeo-jeong,Choi Woo-sik,552778,"53,367,844"
20,https://m.media-amazon.com/images/M/MV5BOTc2ZT...,Soorarai Pottru,2020,U,153 min,Drama,8.6,"Nedumaaran Rajangam ""Maara"" sets out to make t...",NaN,Sudha Kongara,Suriya,Madhavan,Paresh Rawal,Aparna Balamurali,54995,NaN

4. **count()**: The count() function is used to count the non-null (non-missing) values in each column of a DataFrame. It returns the number of non-missing values for each column, effectively giving you an idea of the completeness of your data.

In [5]:
df.count()

Poster_Link      1000
Series_Title     1000
Released_Year    1000
Certificate       899
Runtime          1000
Genre            1000
IMDB_Rating      1000
Overview         1000
Meta_score        843
Director         1000
Star1            1000
Star2            1000
Star3            1000
Star4            1000
No_of_Votes      1000
Gross             831
dtype: int64

5. **describe()**: The describe() function is used to generate descriptive statistics of a DataFrame. It calculates various summary statistics for numerical columns in the DataFrame, such as the mean, standard deviation, minimum, maximum, quartiles, and more. This function provides a quick overview of the distribution and basic characteristics of the numerical data in the DataFrame.

In [6]:
df.describe()

       IMDB_Rating  Meta_score   No_of_Votes
count  1000.000000  843.000000  1.000000e+03
mean      7.949300   77.971530  2.736929e+05
std       0.275491   12.376099  3.273727e+05
min       7.600000   28.000000  2.508800e+04
25%       7.700000   70.000000  5.552625e+04
50%       7.900000   79.000000  1.385485e+05
75%       8.100000   87.000000  3.741612e+05
max       9.300000  100.000000  2.343110e+06

6. **transpose()**: The transpose() function is used to interchange rows and columns of a DataFrame. It effectively flips the DataFrame along its diagonal axis, turning rows into columns and columns into rows.

In [7]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
Poster_Link,https://m.media-amazon.com/images/M/MV5BMDFkYT...,https://m.media-amazon.com/images/M/MV5BM2MyNj...,https://m.media-amazon.com/images/M/MV5BMTMxNT...,https://m.media-amazon.com/images/M/MV5BMWMwMG...,https://m.media-amazon.com/images/M/MV5BMWU4N2...,https://m.media-amazon.com/images/M/MV5BNzA5ZD...,https://m.media-amazon.com/images/M/MV5BNGNhMD...,https://m.media-amazon.com/images/M/MV5BNDE4OT...,https://m.media-amazon.com/images/M/MV5BMjAxMz...,https://m.media-amazon.com/images/M/MV5BMmEzNT...,...,https://m.media-amazon.com/images/M/MV5BYjRmY2...,https://m.media-amazon.com/images/M/MV5BMzAyND...,https://m.media-amazon.com/images/M/MV5BMjAwMT...,https://m.media-amazon.com/images/M/MV5BYTE4YW...,https://m.media-amazon.com/images/M/MV5BZjQyMG...,https://m.media-amazon.com/images/M/MV5BNGEwMT...,https://m.media-amazon.com/images/M/MV5BODk3Yj...,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,https://m.media-amazon.com/images/M/MV5BZTBmMj...,https://m.media-amazon.com/images/M/MV5BMTY5OD...
Series_Title,The Shawshank Redemption,The Godfather,The Dark Knight,The Godfather: Part II,12 Angry Men,The Lord of the Rings: The Return of the King,Pulp Fiction,Schindler's List,Inception,Fight Club,...,Giù la testa,Kelly's Heroes,The Jungle Book,Blowup,A Hard Day's Night,Breakfast at Tiffany's,Giant,From Here to Eternity,Lifeboat,The 39 Steps
Released_Year,1994,1972,2008,1974,1957,2003,1994,1993,2010,1999,...,1971,1970,1967,1966,1964,1961,1956,1953,1944,1935
Certificate,A,A,UA,A,U,U,A,A,UA,A,...,PG,GP,U,A,U,A,G,Passed,NaN,NaN
Runtime,142 min,175 min,152 min,202 min,96 min,201 min,154 min,195 min,148 min,139 min,...,157 min,144 min,78 min,111 min,87 min,115 min,201 min,118 min,97 min,86 min
Genre,Drama,"Crime, Drama","Action, Crime, Drama","Crime, Drama","Crime, Drama","Action, Adventure, Drama","Crime, Drama","Biography, Drama, History","Action, Adventure, Sci-Fi",Drama,...,"Drama, War, Western","Adventure, Comedy, War","Animation, Adventure, Family","Drama, Mystery, Thriller","Comedy, Music, Musical","Comedy, Drama, Romance","Drama, Western","Drama, Romance, War","Drama, War","Crime, Mystery, Thriller"
IMDB_Rating,9.3,9.2,9.0,9.0,9.0,8.9,8.9,8.9,8.8,8.8,...,7.6,7.6,7.6,7.6,7.6,7.6,7.6,7.6,7.6,7.6
Overview,Two imprisoned men bond over a number of years...,An organized crime dynasty's aging patriarch t...,When the menace known as the Joker wreaks havo...,The early life and career of Vito Corleone in ...,A jury holdout attempts to prevent a miscarria...,Gandalf and Aragorn lead the World of Men agai...,"The lives of two mob hitmen, a boxer, a gangst...","In German-occupied Poland during World War II,...",A thief who steals corporate secrets through t...,An insomniac office worker and a devil-may-car...,...,A low-life bandit and an I.R.A. explosives exp...,A group of U.S. soldiers sneaks across enemy l...,Bagheera the Panther and Baloo the Bear have a...,A fashion photographer unknowingly captures a ...,"Over two ""typical"" days in the life of The Bea...",A young New York socialite becomes interested ...,Sprawling epic covering the life of a Texas ca...,"In Hawaii in 1941, a private is cruelly punish...",Several survivors of a torpedoed merchant ship...,A man in London tries to help a counter-espion...
Meta_score,80.0,100.0,84.0,90.0,96.0,94.0,94.0,94.0,74.0,66.0,...,77.0,50.0,65.0,82.0,96.0,76.0,84.0,85.0,78.0,93.0
Director,Frank Darabont,Francis Ford Coppola,Christopher Nolan,Francis Ford Coppola,Sidney Lumet,Peter Jackson,Quentin Tarantino,Steven Spielberg,Christopher Nolan,David Fincher,...,Sergio Leone,Brian G. Hutton,Wolfgang Reitherman,Michelangelo Antonioni,Richard Lester,Blake Edwards,George Stevens,Fred Zinnemann,Alfred Hitchcock,Alfred Hitchcock
Star1,Tim Robbins,Marlon Brando,Christian Bale,Al Pacino,Henry Fonda,Elijah Wood,John Travolta,Liam Neeson,Leonardo DiCaprio,Brad Pitt,...,Rod Steiger,Clint Eastwood,Phil Harris,David Hemmings,John Lennon,Audrey Hepburn,Elizabeth Taylor,Burt Lancaster,Tallulah Bankhead,Robert Donat
Star2,Morgan Freeman,Al Pacino,Heath Ledger,Robert De Niro,Lee J. Cobb,Viggo Mortensen,Uma Thurman,Ralph Fiennes,Joseph Gordon-Levitt,Edward Norton,...,James Coburn,Telly Savalas,Sebastian Cabot,Vanessa Redgrave,Paul McCartney,George Peppard,Rock Hudson,Montgomery Clift,John Hodiak,Madeleine Carroll
Star3,Bob Gunton,James Caan,Aaron Eckhart,Robert Duvall,Martin Balsam,Ian McKellen,Samuel L. Jackson,Ben Kingsley,Elliot Page,Meat Loaf,...,Romolo Valli,Don Rickles,Louis Prima,Sarah Miles,George Harrison,Patricia Neal,James Dean,Deborah Kerr,Walter Slezak,Lucie Mannheim
Star4,William Sadler,Diane Keaton,Michael Caine,Diane Keaton,John Fiedler,Orlando Bloom,Bruce Willis,Caroline Goodall,Ken Watanabe,Zach Grenier,...,Maria Monti,Carroll O'Connor,Bruce Reitherman,John Castle,Ringo Starr,Buddy Ebsen,Carroll Baker,Donna Reed,William Bendix,Godfrey Tearle
No_of_Votes,2343110,1620367,2303232,1129952,689845,1642758,1826188,1213505,2067042,1854740,...,30144,45338,166409,56513,40351,166544,34075,43374,26471,51853
Gross,"28,341,469","134,966,411","534,858,444","57,300,000","4,360,000","377,845,905","107,928,762","96,898,818","292,576,195","37,030,102",...,"696,690","1,378,435","141,843,612",NaN,"13,780,024",NaN,NaN,"30,500,000",NaN,NaN

**Conclusion**: Hence, From this experiment We've learned how to load a dataset, access specific rows and columns, count non-null values, generate summary statistics, and transpose data.